<x-layouts.app title="Discipleship Report">
    @php $statusLabel = static fn (string $status) => str($status)->replace('_', ' ')->title(); @endphp
    <section class="space-y-6">
        <div class="flex flex-wrap items-center justify-between gap-3">
            <div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-xl" style="background:rgba(124,58,237,.14); color:rgb(124,58,237);"><i class="fas fa-book-open"></i></span><div><h3 class="text-2xl font-semibold text-[var(--color-ink-950)]">Discipleship Report</h3><p class="text-xs text-slate-500">Foundation progression, completion, and certificate awards</p></div></div>
            <div class="flex items-center gap-2 print-hide"><a href="{{ route('reports.discipleship.export', request()->query()) }}" class="btn-secondary flex items-center gap-1.5"><i class="fas fa-download text-xs"></i> Export CSV</a><button onclick="window.print()" class="btn-secondary flex items-center gap-1.5"><i class="fas fa-print text-xs"></i> Print</button><a href="{{ route('reports.index') }}" class="btn-secondary">All reports</a></div>
        </div>

        <x-ui.date-range-filters :action="route('reports.discipleship')" :date-from="$dateFrom" :date-to="$dateTo" />

        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <article class="stat-card p-5"><p class="text-xs uppercase tracking-[.14em] text-slate-500">Enrolled</p><p class="mt-1 text-3xl font-bold">{{ number_format($total) }}</p><p class="mt-1 text-xs text-slate-500">All participants</p></article>
            <article class="stat-card p-5"><p class="text-xs uppercase tracking-[.14em] text-slate-500">Registered Members</p><p class="mt-1 text-3xl font-bold">{{ number_format($registeredMembers) }}</p><p class="mt-1 text-xs text-slate-500">Linked to member records</p></article>
            <article class="stat-card p-5"><p class="text-xs uppercase tracking-[.14em] text-slate-500">Foundation Completed</p><p class="mt-1 text-3xl font-bold text-emerald-500">{{ number_format($completed) }}</p><p class="mt-1 text-xs text-slate-500">Finished all four stages</p></article>
            <article class="stat-card p-5"><p class="text-xs uppercase tracking-[.14em] text-slate-500">Certificates Awarded</p><p class="mt-1 text-3xl font-bold text-violet-500">{{ number_format($awarded) }}</p><p class="mt-1 text-xs text-slate-500">Recognised graduates</p></article>
        </div>

        <div class="grid gap-6 lg:grid-cols-2">
            <article class="surface-card p-6"><h4 class="mb-4 font-semibold text-[var(--color-ink-950)]">Foundation stage progress</h4><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="text-left text-xs uppercase text-slate-500"><tr><th class="pb-3">Stage</th><th class="pb-3 text-right">Not started</th><th class="pb-3 text-right">Started</th><th class="pb-3 text-right">In progress</th><th class="pb-3 text-right">Completed</th></tr></thead><tbody class="divide-y divide-[var(--color-surface-200)]">@for ($stage = 1; $stage <= 4; $stage++) @php($counts = $stageBreakdown->get($stage, collect()))<tr><td class="py-3 font-medium">Foundation {{ $stage }}</td><td class="py-3 text-right">{{ $counts->get('not_started', 0) }}</td><td class="py-3 text-right">{{ $counts->get('started', 0) }}</td><td class="py-3 text-right">{{ $counts->get('in_progress', 0) }}</td><td class="py-3 text-right font-medium text-emerald-600">{{ $counts->get('completed', 0) }}</td></tr>@endfor</tbody></table></div></article>
            <article class="surface-card p-6"><h4 class="mb-3 font-semibold text-[var(--color-ink-950)]">Programme outcome</h4><div class="space-y-4"><div><div class="flex justify-between text-sm"><span>Foundation completion</span><span>{{ $total ? round($completed / $total * 100, 1) : 0 }}%</span></div><div class="mt-1 h-2 rounded-full bg-slate-100"><div class="h-full rounded-full bg-emerald-500" style="width:{{ $total ? round($completed / $total * 100, 1) : 0 }}%"></div></div></div><div><div class="flex justify-between text-sm"><span>Certificates awarded</span><span>{{ $total ? round($awarded / $total * 100, 1) : 0 }}%</span></div><div class="mt-1 h-2 rounded-full bg-slate-100"><div class="h-full rounded-full bg-violet-500" style="width:{{ $total ? round($awarded / $total * 100, 1) : 0 }}%"></div></div></div><p class="text-sm text-slate-500">{{ number_format($total - $registeredMembers) }} external participant{{ $total - $registeredMembers === 1 ? '' : 's' }} enrolled during this period.</p></div></article>
        </div>

        <article class="surface-card p-6"><h4 class="mb-4 font-semibold text-[var(--color-ink-950)]">Participants</h4><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="border-b border-[var(--color-surface-200)] text-left text-xs uppercase text-slate-500"><tr><th class="pb-3">Participant</th><th class="pb-3">Type</th>@for ($stage = 1; $stage <= 4; $stage++)<th class="pb-3">F{{ $stage }}</th>@endfor<th class="pb-3">Certificate</th></tr></thead><tbody class="divide-y divide-[var(--color-surface-200)]">@forelse ($participants as $participant)<tr><td class="py-3 font-medium">{{ $participant->display_name }}</td><td class="py-3 text-slate-500">{{ $participant->member_id ? 'Member' : 'External' }}</td>@for ($stage = 1; $stage <= 4; $stage++)<td class="py-3 text-slate-500">{{ $statusLabel($participant->stages->firstWhere('stage_number', $stage)?->status ?? 'not_started') }}</td>@endfor<td class="py-3">{{ $participant->certificate_number ?: '—' }}</td></tr>@empty<tr><td colspan="7" class="py-8 text-center text-slate-400">No participants found for this period.</td></tr>@endforelse</tbody></table></div></article>
    </section>
</x-layouts.app>
