<?php

return [
    'permissions' => [
        'expenditures.read',
        'expenditures.create',
        'expenditures.update',
        'expenditures.delete',
        'dashboard.read',
        'dashboard.admin_kpis',
        'dashboard.finance_kpis',
        'dashboard.membership_kpis',
        'members.read',
        'members.create',
        'members.update',
        'members.delete',
        'members.export',
        'members.import',
        'families.read',
        'families.create',
        'families.update',
        'families.delete',
        'families.export',
        'families.import',
        'donations.read',
        'donations.create',
        'donations.update',
        'donations.delete',
        'donations.export',
        'donations.approve',
        'campaigns.read',
        'campaigns.create',
        'campaigns.update',
        'campaigns.delete',
        'campaigns.export',
        'campaigns.approve',
        'income.read',
        'income.create',
        'income.update',
        'income.delete',
        'payroll.read',
        'payroll.create',
        'payroll.update',
        'payroll.delete',
        'payroll.export',
        'payroll.approve',
        'payroll.categories.manage',
        'pledges.read',
        'pledges.create',
        'pledges.update',
        'pledges.delete',
        'pledges.export',
        'pledges.approve',
        'pledge_payments.read',
        'pledge_payments.create',
        'pledge_payments.update',
        'reports.read',
        'reports.financial.read',
        'reports.membership.read',
        'reports.export',
        'departments.read',
        'departments.create',
        'departments.update',
        'departments.delete',
        'zones.read',
        'zones.create',
        'zones.update',
        'zones.delete',
        'visitors.read',
        'visitors.create',
        'visitors.update',
        'visitors.delete',
        'visitors.convert',
        'follow_up.read',
        'follow_up.create',
        'follow_up.update',
        'follow_up.delete',
        'attendance.read',
        'attendance.create',
        'attendance.update',
        'attendance.delete',
        'attendance.reports.read',
        'pastoral_care.read',
        'pastoral_care.create',
        'pastoral_care.update',
        'pastoral_care.delete',
        'pastoral_care.notes.create',
        'prayer_requests.read',
        'prayer_requests.create',
        'prayer_requests.update',
        'prayer_requests.delete',
        'alerts.read',
        'alerts.run',
        'alerts.update',
        'alerts.delete',
        'member_timeline.read',
        'leaders.read',
        'leaders.create',
        'leaders.update',
        'leaders.delete',
        'events.read',
        'events.create',
        'events.update',
        'events.delete',
        'volunteers.read',
        'volunteers.create',
        'volunteers.update',
        'volunteers.delete',
        'communications.read',
        'communications.create',
        'communications.update',
        'communications.delete',
        'communications.send',
        'scorecards.read',
        'users.read',
        'users.create',
        'users.update',
        'users.delete',
        'users.assign_roles',
        'roles.read',
        'roles.update',
        'audit_logs.read',
        'settings.manage',
    ],
    'roles' => [
        'system_admin' => [
            'name' => 'System Admin',
            'description' => 'Full access to the church management system.',
            'permissions' => ['*'],
        ],
        'pastor' => [
            'name' => 'Pastor',
            'description' => 'Senior leadership — ministry oversight, approvals, active pastoral work, and church communications.',
            'permissions' => [
                // Core
                'dashboard.read',
                'dashboard.admin_kpis',
                'dashboard.finance_kpis',
                'dashboard.membership_kpis',
                'scorecards.read',
                'reports.read',
                'reports.financial.read',
                'reports.membership.read',
                'reports.export',
                // People — read only
                'members.read',
                'members.export',
                'families.read',
                'families.export',
                'departments.read',
                'zones.read',
                'visitors.read',
                'visitors.convert',
                'follow_up.read',
                'follow_up.create',
                'leaders.read',
                'member_timeline.read',
                // Ministry — active role
                'attendance.read',
                'attendance.reports.read',
                'pastoral_care.read',
                'pastoral_care.create',
                'pastoral_care.update',
                'pastoral_care.delete',
                'pastoral_care.notes.create',
                'prayer_requests.read',
                'prayer_requests.create',
                'prayer_requests.update',
                'prayer_requests.delete',
                'alerts.read',
                'alerts.run',
                'events.read',
                'events.create',
                'events.update',
                'events.delete',
                'volunteers.read',
                'communications.read',
                'communications.create',
                'communications.update',
                'communications.delete',
                'communications.send',
                // Finance — read + approve only
                'income.read',
                'expenditures.read',
                'donations.read',
                'donations.export',
                'donations.approve',
                'campaigns.read',
                'campaigns.export',
                'campaigns.approve',
                'payroll.read',
                'payroll.export',
                'payroll.approve',
                'pledges.read',
                'pledges.export',
                'pledges.approve',
                'pledge_payments.read',
                // Admin visibility
                'audit_logs.read',
            ],
        ],
        'finance_officer' => [
            'name' => 'Finance Officer',
            'description' => 'Full ownership of all financial records — income, giving, payroll, expenditures, campaigns, and financial reports.',
            'permissions' => [
                // Core
                'dashboard.read',
                'dashboard.finance_kpis',
                'reports.read',
                'reports.financial.read',
                'reports.export',
                // People — read only (to identify donors/payees)
                'members.read',
                'families.read',
                // Ministry — events read for revenue context
                'events.read',
                // Finance — full CRUD + approve
                'expenditures.read',
                'expenditures.create',
                'expenditures.update',
                'expenditures.delete',
                'income.read',
                'income.create',
                'income.update',
                'income.delete',
                'payroll.read',
                'payroll.create',
                'payroll.update',
                'payroll.delete',
                'payroll.export',
                'payroll.approve',
                'payroll.categories.manage',
                'donations.read',
                'donations.create',
                'donations.update',
                'donations.delete',
                'donations.export',
                'donations.approve',
                'campaigns.read',
                'campaigns.create',
                'campaigns.update',
                'campaigns.delete',
                'campaigns.export',
                'campaigns.approve',
                'pledges.read',
                'pledges.create',
                'pledges.update',
                'pledges.delete',
                'pledges.export',
                'pledges.approve',
                'pledge_payments.read',
                'pledge_payments.create',
                'pledge_payments.update',
                // Admin visibility
                'audit_logs.read',
            ],
        ],
        'church_secretary' => [
            'name' => 'Church Secretary',
            'description' => 'Day-to-day operations — people records, attendance, ministry, events, communications, and coordination.',
            'permissions' => [
                // Core
                'dashboard.read',
                'dashboard.membership_kpis',
                'scorecards.read',
                'reports.read',
                'reports.membership.read',
                'reports.export',
                // People — full CRUD
                'members.read',
                'members.create',
                'members.update',
                'members.delete',
                'members.export',
                'members.import',
                'families.read',
                'families.create',
                'families.update',
                'families.delete',
                'families.export',
                'families.import',
                'departments.read',
                'departments.create',
                'departments.update',
                'departments.delete',
                'zones.read',
                'zones.create',
                'zones.update',
                'zones.delete',
                'leaders.read',
                'leaders.create',
                'leaders.update',
                'leaders.delete',
                'visitors.read',
                'visitors.create',
                'visitors.update',
                'visitors.delete',
                'visitors.convert',
                'follow_up.read',
                'follow_up.create',
                'follow_up.update',
                'follow_up.delete',
                'member_timeline.read',
                // Ministry — full CRUD
                'attendance.read',
                'attendance.create',
                'attendance.update',
                'attendance.delete',
                'attendance.reports.read',
                'pastoral_care.read',
                'pastoral_care.create',
                'pastoral_care.update',
                'pastoral_care.notes.create',
                'prayer_requests.read',
                'prayer_requests.create',
                'prayer_requests.update',
                'prayer_requests.delete',
                'alerts.read',
                'alerts.run',
                'alerts.update',
                'alerts.delete',
                'events.read',
                'events.create',
                'events.update',
                'events.delete',
                'volunteers.read',
                'volunteers.create',
                'volunteers.update',
                'volunteers.delete',
                'communications.read',
                'communications.create',
                'communications.update',
                'communications.delete',
                'communications.send',
                // Finance — read only (public campaign visibility)
                'campaigns.read',
                // Admin visibility
                'audit_logs.read',
            ],
        ],
        'zone_leader' => [
            'name' => 'Zone Leader',
            'description' => 'Cell/zone group leadership — attendance, follow-up, pastoral care, and prayer for their group.',
            'permissions' => [
                // Core
                'dashboard.read',
                'member_timeline.read',
                // People — read only, limited create
                'members.read',
                'families.read',
                'zones.read',
                'visitors.read',
                'visitors.create',
                'visitors.update',
                'follow_up.read',
                'follow_up.create',
                'follow_up.update',
                // Ministry — scoped to their group
                'attendance.read',
                'attendance.create',
                'pastoral_care.read',
                'pastoral_care.create',
                'pastoral_care.notes.create',
                'prayer_requests.read',
                'prayer_requests.create',
                'prayer_requests.update',
                'events.read',
                'alerts.read',
            ],
        ],
        'usher' => [
            'name' => 'Usher',
            'description' => 'Door volunteer — QR scan check-in, visitor registration, and attendance recording only.',
            'permissions' => [
                'attendance.create',
                'members.read',
                'events.read',
                'visitors.create',
            ],
        ],
    ],
    'navigation' => [
        [
            'label' => 'Dashboard',
            'route' => 'dashboard.index',
            'permission' => 'dashboard.read',
        ],
        [
            'label' => 'Users',
            'route' => 'users.index',
            'permission' => 'users.read',
        ],
        [
            'label' => 'Members',
            'route' => 'members.index',
            'permission' => 'members.read',
        ],
        [
            'label' => 'Families',
            'route' => 'families.index',
            'permission' => 'families.read',
        ],
        [
            'label' => 'Departments',
            'route' => 'departments.index',
            'permission' => 'departments.read',
        ],
        [
            'label' => 'Zones',
            'route' => 'zones.index',
            'permission' => 'zones.read',
        ],
        [
            'label' => 'Visitors',
            'route' => 'visitors.index',
            'permission' => 'visitors.read',
        ],
        [
            'label' => 'Follow-Up',
            'route' => 'follow-up.index',
            'permission' => 'follow_up.read',
        ],
        [
            'label' => 'Leaders',
            'route' => 'leaders.index',
            'permission' => 'leaders.read',
        ],
        [
            'label' => 'Attendance',
            'route' => 'attendance.index',
            'permission' => 'attendance.read',
        ],
        [
            'label' => 'Pastoral Care',
            'route' => 'pastoral-care.index',
            'permission' => 'pastoral_care.read',
        ],
        [
            'label' => 'Prayer Requests',
            'route' => 'prayer-requests.index',
            'permission' => 'prayer_requests.read',
        ],
        [
            'label' => 'Alerts',
            'route' => 'alerts.index',
            'permission' => 'alerts.read',
        ],
        [
            'label' => 'Communications',
            'route' => 'communications.index',
            'permission' => 'communications.read',
        ],
        [
            'label' => 'Events',
            'route' => 'events.index',
            'permission' => 'events.read',
        ],
        [
            'label' => 'Volunteers',
            'route' => 'volunteers.index',
            'permission' => 'volunteers.read',
        ],
        [
            'label' => 'Scorecards',
            'route' => 'scorecards.index',
            'permission' => 'scorecards.read',
        ],
        [
            'label' => 'Reports',
            'route' => 'reports.index',
            'permission' => 'reports.read',
        ],
        [
            'label' => 'Executive',
            'route' => 'dashboard.executive',
            'permission' => 'dashboard.admin_kpis',
        ],
        // --- Phase 1: Core Finance Modules ---
        [
            'label' => 'Payroll',
            'route' => 'payroll.index',
            'permission' => 'payroll.read',
        ],
        [
            'label' => 'Expenditures',
            'route' => 'expenditures.index',
            'permission' => 'expenditures.read',
        ],
        [
            'label' => 'Department Income',
            'route' => 'department-income.index',
            'permission' => 'departments.read',
        ],
        [
            'label' => 'Department Expenses',
            'route' => 'department-expenses.index',
            'permission' => 'departments.read',
        ],
        [
            'label' => 'Income Records',
            'route' => 'income.index',
            'permission' => 'income.read',
        ],
        [
            'label' => 'Income Types',
            'route' => 'income-types.index',
            'permission' => 'income.read',
        ],
        [
            'label' => 'Payroll Categories',
            'route' => 'payroll-categories.index',
            'permission' => 'payroll.read',
        ],
        // --- Phase 2: Giving & Campaigns ---
        [
            'label' => 'Donations',
            'route' => 'donations.index',
            'permission' => 'donations.read',
        ],
        [
            'label' => 'Campaigns',
            'route' => 'campaigns.index',
            'permission' => 'campaigns.read',
        ],
        [
            'label' => 'Pledges',
            'route' => 'pledges.index',
            'permission' => 'pledges.read',
        ],
        [
            'label' => 'Missed Pledges',
            'route' => 'missed-pledges.index',
            'permission' => 'pledges.read',
        ],
        [
            'label' => 'Pledge Payments',
            'route' => 'pledge-payments.index',
            'permission' => 'pledge_payments.read',
        ],
        [
            'label' => 'Role Permissions',
            'route' => 'roles.index',
            'permission' => 'roles.read',
        ],
        [
            'label' => 'Audit Log',
            'route' => 'audit-logs.index',
            'permission' => 'audit_logs.read',
        ],
    ],
];
