<x-layouts.app title="Enrol in Discipleship">
    <section class="surface-card mx-auto max-w-3xl p-6">
        <div class="flex items-center justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.24em] text-slate-400">Discipleship</p><h3 class="text-xl font-semibold text-[var(--color-ink-950)]">Enrol participant</h3></div><a href="{{ route('discipleship.index') }}" class="btn-secondary">Back</a></div>
        <form method="POST" action="{{ route('discipleship.store') }}" class="mt-6 space-y-6">@csrf
            <div class="rounded-xl border border-violet-100 bg-violet-50/50 p-4"><label class="mb-1 block text-sm font-medium text-slate-700">Registered member</label><select name="member_id" class="form-input"><option value="">Select from members, or use external participant below</option>@foreach ($members as $member)<option value="{{ $member->id }}" @selected(old('member_id') == $member->id)>{{ $member->full_name }}{{ $member->phone ? ' — '.$member->phone : '' }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">Selecting a member uses their registry profile for the programme.</p>@error('member_id')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <div><h4 class="font-medium text-[var(--color-ink-950)]">External participant</h4><p class="mt-1 text-xs text-slate-500">Complete this section only when the person is not yet a registered member.</p><div class="mt-3 grid gap-4 md:grid-cols-2"><div><label class="mb-1 block text-sm font-medium">Full name</label><input name="external_name" class="form-input" value="{{ old('external_name') }}">@error('external_name')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div><div><label class="mb-1 block text-sm font-medium">Phone</label><input name="external_phone" class="form-input" value="{{ old('external_phone') }}"></div><div class="md:col-span-2"><label class="mb-1 block text-sm font-medium">Email</label><input type="email" name="external_email" class="form-input" value="{{ old('external_email') }}"></div></div></div>
            <div><label class="mb-1 block text-sm font-medium">Remarks</label><textarea name="remarks" rows="3" class="form-input">{{ old('remarks') }}</textarea></div>
            <div class="flex justify-end gap-2"><a href="{{ route('discipleship.index') }}" class="btn-secondary">Cancel</a><button class="btn-primary">Enrol participant</button></div>
        </form>
    </section>
</x-layouts.app>
