<x-layouts.app :title="$participant->display_name.' — Discipleship'">
    @php $label = static fn (string $value) => str($value)->replace('_', ' ')->title(); @endphp
    <section class="surface-card p-6">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><a href="{{ route('discipleship.index') }}" class="text-sm text-slate-500"><i class="fas fa-arrow-left mr-1"></i>Discipleship</a><h3 class="mt-2 text-xl font-semibold text-[var(--color-ink-950)]">{{ $participant->display_name }}</h3><p class="mt-1 text-sm text-slate-500">{{ $participant->member ? 'Registered member' : 'External participant' }} · {{ $participant->member?->phone ?: $participant->external_phone ?: 'No phone' }}</p></div>@if ($participant->certificate_awarded_at)<div class="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700"><i class="fas fa-award mr-1"></i>Certificate {{ $participant->certificate_number }} awarded {{ $participant->certificate_awarded_at->format('d M Y') }}</div>@endif</div>

        <div class="mt-6 grid gap-4 lg:grid-cols-2">
            @foreach ($participant->stages as $stage)
                <article class="rounded-xl border border-[var(--color-surface-200)] p-5"><div class="flex items-center justify-between"><h4 class="font-semibold text-[var(--color-ink-950)]">Foundation {{ $stage->stage_number }}</h4><span class="rounded-full bg-violet-50 px-2.5 py-1 text-xs font-medium text-violet-700">{{ $label($stage->status) }}</span></div>
                    @can('discipleship.update')<form method="POST" action="{{ route('discipleship.stages.update', [$participant, $stage]) }}" class="mt-4 grid gap-3">@csrf @method('PUT')<select name="status" class="form-input">@foreach ($statuses as $status)<option value="{{ $status }}" @selected($stage->status === $status)>{{ $label($status) }}</option>@endforeach</select><div class="grid grid-cols-2 gap-3"><input type="date" name="started_at" class="form-input" value="{{ $stage->started_at?->toDateString() }}"><input type="date" name="completed_at" class="form-input" value="{{ $stage->completed_at?->toDateString() }}"></div><textarea name="notes" rows="2" class="form-input" placeholder="Class notes">{{ $stage->notes }}</textarea><button class="btn-secondary justify-self-start text-sm">Save stage</button></form>@else <p class="mt-3 text-sm text-slate-500">Started: {{ $stage->started_at?->format('d M Y') ?: '—' }} · Completed: {{ $stage->completed_at?->format('d M Y') ?: '—' }}</p>@endcan
                </article>
            @endforeach
        </div>

        <div class="mt-6 rounded-xl border border-[var(--color-surface-200)] p-5"><h4 class="font-semibold text-[var(--color-ink-950)]">Foundation completion certificate</h4>@if ($participant->certificate_awarded_at)<p class="mt-1 text-sm text-emerald-600">Awarded as {{ $participant->certificate_number }}.</p>@elseif ($participant->has_completed_foundation)<p class="mt-1 text-sm text-slate-500">All four Foundation stages are complete and this participant is eligible.</p>@can('discipleship.award')<form method="POST" action="{{ route('discipleship.certificate.award', $participant) }}" class="mt-3">@csrf<button class="btn-primary"><i class="fas fa-award mr-1"></i>Award certificate</button></form>@endcan @else <p class="mt-1 text-sm text-slate-500">Complete all four Foundation stages to make this participant eligible.</p>@endif</div>
    </section>
</x-layouts.app>
